// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

// FIREBASE DATA ACTIONS
export const UPDATE_RSVP = 'UPDATE_RSVP';
export const FETCH_RSVP = 'FETCH_RSVP';

// COPY
export const SWITCH_LANG = 'SWITCH_LANG';

// STORY QUIZ
export const ANSWER_STORY_QUIZ = 'ANSWER_STORY_QUIZ';
export const RETRY_STORY_QUIZ = 'RETRY_STORY_QUIZ';
